common/models/Product.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $sku
 * @property string $name
 * @property string $description
 * @property double $price
 * @property double $retail_price
 * @property string $image
 * @property string $brand
 * @property string $slug
 * @property string $flavour
 * @property string $size
 * @property string $combination_id
 * @property string $meta_title
 * @property string $meta_description
 * @property string $meta_keyword
 * @property string $import_url
 * @property int $is_active
 * @property int $created_at
 * @property int $updated_at
 *
 * @property MapProductCategory[] $mapProductCategories
 * @property ProductCombination[] $productCombinations
 * @property ProductCombination[] $productCombinations0
 * @property ProductRelated[] $productRelateds
 * @property ProductRelated[] $productRelateds0
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // [['sku', 'name', 'description', 'price', 'retail_price', 'image', 'brand', 'slug', 'flavour', 'size', 'meta_title', 'meta_description', 'meta_keyword', 'import_url', 'created_at', 'updated_at'], 'required'],
            [['description', 'meta_title', 'meta_description', 'meta_keyword', 'import_url'], 'string'],
            [['price', 'retail_price'], 'number'],
            [['is_active', 'created_at', 'updated_at'], 'integer'],
            [['sku', 'name', 'image', 'slug', 'flavour', 'size', 'combination_id'], 'string', 'max' => 255],
            [['brand'], 'string', 'max' => 70],
            [['sku'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sku' => 'Sku',
            'name' => 'Name',
            'description' => 'Description',
            'price' => 'Price',
            'retail_price' => 'Retail Price',
            'image' => 'Image',
            'brand' => 'Brand',
            'slug' => 'Slug',
            'flavour' => 'Flavour',
            'size' => 'Size',
            'combination_id' => 'Combination ID',
            'meta_title' => 'Meta Title',
            'meta_description' => 'Meta Description',
            'meta_keyword' => 'Meta Keyword',
            'import_url' => 'Import Url',
            'is_active' => 'Is Active',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMapProductCategories()
    {
        return $this->hasMany(MapProductCategory::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductCombinations()
    {
        return $this->hasMany(ProductCombination::className(), ['child_product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductCombinations0()
    {
        return $this->hasMany(ProductCombination::className(), ['parent_product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductRelateds()
    {
        return $this->hasMany(ProductRelated::className(), ['child_product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductRelateds0()
    {
        return $this->hasMany(ProductRelated::className(), ['parent_product_id' => 'id']);
    }
}

backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\AdminProduct;
use app\models\AdminProductSearch;
use \common\models\ProductCategory;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index','view','create','update','delete'],
                'rules' => [               
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $searchModel = new AdminProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionCreate()
    {
        $model = new AdminProduct();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if(!empty($_POST['categoty_id'])){
                foreach($_POST['categoty_id'] as $category_id){
                     $ProductCategory = new ProductCategory;
                     $ProductCategory->category_id = $category_id;
                     $ProductCategory->product_id = $model->id;
                     $ProductCategory->save(false);
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'ProductCategory'=>array()
        ]);
    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $ProductCategory = ArrayHelper::map(ProductCategory::find()->where(['product_id'=>$id])->asArray()->all(),'category_id','category_id');
      
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
           if(!empty($_POST['categoty_id'])){
               Yii::$app->db->createCommand('DELETE FROM `map_product_category` WHERE `product_id`=:product_id')->bindValue(':product_id',$model->id)->execute();
               foreach($_POST['categoty_id'] as $category_id){
                    $ProductCategory = new ProductCategory;
                    $ProductCategory->category_id = $category_id;
                    $ProductCategory->product_id = $model->id;
                    $ProductCategory->save(false);
               }
           }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update',[
            'model' => $model,
            'ProductCategory'=>$ProductCategory
        ]);
    }
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    protected function findModel($id)
    {
        if (($model = AdminProduct::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/ProductController.php
<?php

namespace frontend\controllers;
use \common\models\Product;
use \common\models\Category;
use \common\models\ProductCombination;

use \common\models\ProductCategory;
use \common\models\ProductRelated;
use yii\helpers\ArrayHelper;
use Yii;

class ProductController extends \yii\web\Controller
{
	public $enableCsrfValidation = false;
    public function actionCategory($slug){
        $Category             =  Category::find()->where(['slug'=>$slug])->asArray()->one();
        return $this->render('categoryProduct',[
            'Category'   =>  $Category,
        ]);
    }
	public function actionLoadProducts(){
        $limit        = !empty($_POST['limit'])?$_POST['limit']:0;
        $category_id  = !empty($_POST['category_id'])?$_POST['category_id']:0;

        $CategoryIds   = ArrayHelper::map(Yii::$app->general->recursiveCategory($category_id),'id','id');
        $CategoryIds   =  array($category_id)+$CategoryIds;
        $CategoryIds   = !empty($CategoryIds)?implode(",",$CategoryIds) :array();
        $TotalResult   = ProductCategory::find()->joinWith('product')
                        ->where('map_product_category.category_id IN ('.$CategoryIds.')')->count();
						
		$Products      = ProductCategory::find()->joinWith('product')
                        ->where('map_product_category.category_id IN ('.$CategoryIds.')')
                        ->orderBy(' position asc')->limit(30)->offset($limit)->all();
 	
		$start 				= $limit+1;
		$end 				= $limit+30 >= $TotalResult?$TotalResult: $limit+30;
		$res['TotalResult'] = !empty($TotalResult)?$TotalResult:0;
		$res['summary']     = 'Showing '.($start).' - '.($end).' Of '.$TotalResult;
		$res['html']        = "";
		$res['html']        =   $this->renderAjax('_products',[
							 		'Products'   =>  $Products,
								]);
		if($limit+30 >= $TotalResult){
			$res['status']      = false;
		}else{
			$res['status']      = true;
		}		
		echo json_encode($res);die;
	}
    public function actionView($slug)
    {
        $Product             =  Product::find()->where(['slug'=>$slug])->asArray()->one();
        $ProductCombination  =  ProductCombination::find()->select(['product.slug as slug','product.name as name'])
                                ->leftJoin('product', 'product_combination.child_product_id=product.id')
                                ->where(['product_combination.parent_product_id'=>$Product['id']])
                                ->asArray()->all();
        $ProductRelated      =  ProductRelated::find()->select(['product.*'])
                                ->leftJoin('product', 'product_related.child_product_id=product.id')
                                ->where(['product_related.parent_product_id'=>$Product['id']])
                                ->asArray()->all();
        return $this->render('productDetails',[
            'Product'           =>  $Product,
            'ProductCombination'=>  $ProductCombination,
            'ProductRelated'    =>  $ProductRelated
        ]);
    }


}

frontend/views/product/_bredcumb-category.php
<?php 
use yii\bootstrap\Nav;
use \common\models\Category;
$menuItems   =Yii::$app->general->breadCumb($Category['id']);
$MainMenu   =  Nav::widget([
    'options' => ['class' => 'bredcumb-ul','id'=>''],
    'items' => array_reverse($menuItems),
]);
?>
<section class="breadcrumbArea productpagebreadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul>
                           <?php echo $MainMenu ;?>
                        </ul>

                    </div>
                </div>
            </div>
</section>

frontend/views/product/_bredcumb.php
<?php 

use yii\bootstrap\Nav;

use \common\models\ProductCategory;

use \common\models\Category;

$Category       = ProductCategory::find()->where(['product_id'=>$Product['id']])->one();

$menuItems[]   = ['label' =>$Product['name'], 'url' =>'#','options'=> []];

$menuItems      = $menuItems+Yii::$app->general->breadCumb($Category['category_id']);



$MainMenu   =  Nav::widget([

    'options' => ['class' => 'bredcumb-ul','id'=>''],

    'items' => array_reverse($menuItems),

]);

?>

frontend/views/product/_products.php
<?php

use yii\helpers\Html;

use yii\helpers\HtmlPurifier;

use yii\widgets\Pjax;
if(!empty($Products)){
	foreach($Products as $model){
?>


    <div class="cat-product-con" id="<?=$model->product->sku;?>">

        <div class="catImg">

            <?= Html::a(Html::img(str_replace("500",150,$model->product->image)), array('/product/view','slug'=>$model->product->slug),['target'=>'_blank']); ?>

        </div>

        <h1>
            <?= Html::a(Html::encode($model->product->name),array('/product/view','slug'=>$model->product->slug),['target'=>'_blank']); ?>
        </h1>

        <h5 class="c-price">Rs
            <?= Html::encode($model->product->retail_price);?>
        </h5>

        <h5 class="sale-price">Sale Rs
            <?= Html::encode($model->product->price);?>
        </h5>

        <?= Html::a('Add to Cart', array('/cart/add-to-cart','sku'=>$model->product->sku,'_pjax'=>'#p0'),['class'=>"addtocart",'data-sku'=>$model->product->sku]);?>
            <div class="spin-Div hide">
                <i class="fa fa-spinner fa-spin" style="font-size:24px"></i>
            </div>
    </div>
<?php } } ?>

frontend/views/product/categoryProduct.php
<?php

use yii\helpers\Html;

use yii\helpers\ArrayHelper;

use yii\bootstrap\Nav;

use yii\widgets\ListView;

use \common\models\Category;

use \common\models\ProductCategory;

use yii\data\ActiveDataProvider;

use yii\widgets\Pjax;
$this->title = $Category['meta_title'];
Yii::$app->view->registerMetaTag([
    'name' => 'description',
    'content' => $Category['meta_description']
]); 
Yii::$app->view->registerMetaTag([
    'name' => 'keywords',
    'content' => $Category['meta_keyword']
]); 

$menuItems     = Yii::$app->general->getChildCategory($Category['id']);
$CategoryIds   = ArrayHelper::map(Yii::$app->general->recursiveCategory($Category['id']),'id','id');
$CategoryIds   =  array($Category['id'])+$CategoryIds;
$CategoryIds   = !empty($CategoryIds)?implode(",",$CategoryIds) :array();

?>

<?= $this->render('_bredcumb-category',['Category'=>$Category]); ?>

<section class="categoryMainContent">
  	<div class="container">
      <div class="row">
    	<div class="col-lg-12 pagetitle">
            <h2><?php echo $Category['name'];?> <small id="summary-text" class="pull-right"></small></h2>
                <?php if (Yii::$app->session->hasFlash('cart_success')): ?>
                    <div class="alert alert-success alert-dismissable">
                         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                         <h4><i class="icon fa fa-check"></i>Added!</h4>
                          <?= Yii::$app->session->getFlash('cart_success') ?>
                    </div>
                <?php endif; ?>
                <?php if (Yii::$app->session->hasFlash('cart_error')): ?>
                    <div class="alert alert-danger alert-dismissable">
                         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                         <h4><i class="icon fa fa-times"></i>Error!</h4>
                          <?= Yii::$app->session->getFlash('cart_error') ?>
                    </div>
                <?php endif; ?>
        </div>
      	<div class="col-lg-3 col-sm-3 col-md-3 leftside">
            <h4 class='filter-title'>Category</h4>
            <?= Nav::widget([
                             'options' => ['class' => 'bredcumb-ul','id'=>''],
                             'items' => $menuItems,
            ]);?>
        </div>
        <div class="col-lg-9 col-sm-9 col-md-9 rightside">
        	<div  id="category-product-list">
            </div>
            <div id="category-product-list-loader" class="col-md-12 text-center">
                <i class="fa fa-spin fa-circle-o-notch fa-2x text-mute"></i>
                <p class="text-mute">Loading more Products...</p>
            </div>
        </div>       
      </div>   
   </div>
</section>  
<?php 
$this->registerJs("
var page = 0; var fl= false;
var loadProducts = function(limit){
		console.log(limit)
		fl= true;
	    $('#category-product-list-loader').show();
        call({ url: '/product/load-products', params: { 'limit':limit,'category_id':'".$Category['id']."'}, type: 'POST' }, function(resp) {      
                    $('#category-product-list-loader').hide();
					$('#category-product-list').append(resp.html); 
				    $('#summary-text').html(resp.summary); 
					if(resp.status == true){	
						fl = false;
					}else{
						fl= true;
					}

        });
}
loadProducts(page);
$(window).scroll(function () {
	if ($(window).scrollTop() > ($(document).height() - $(window).height()-$('footer').height()) && fl==false) {	
		console.log('page:'+page)
		page = page+30;
		loadProducts(page);
	}
});
");

?>

frontend/views/product/productDetails.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;
use \common\models\Product;
?>

<?= $this->render('_bredcumb',['Product'=>$Product]); 
$this->title = $Product['meta_title'];
Yii::$app->view->registerMetaTag([
    'name' => 'description',
    'content' => $Product['meta_description']
]); 
Yii::$app->view->registerMetaTag([
    'name' => 'keywords',
    'content' => $Product['meta_keyword']
]); 

$productCombination = array($Product['slug']=>$Product['name'])+ArrayHelper::map($ProductCombination, 'slug', 'name');
$combination    =   array();
foreach($productCombination as $k=>$p){
    $combination[Url::toRoute(['product/view','slug'=>$k])]  =  $p ;
}
?>
<?php Pjax::begin() ?>
 <section>
            <div class="container">
                <div class="product-main-div">
                    <div class="row">
                         <div class="col-md-12">
                            <?php if (Yii::$app->session->hasFlash('cart_success')): ?>
                            <div class="alert alert-success alert-dismissable">
                                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                <h4><i class="icon fa fa-check"></i>Added!</h4>
                                <?= Yii::$app->session->getFlash('cart_success') ?>
                            </div>
                            <?php endif; ?>
                            <?php if (Yii::$app->session->hasFlash('cart_error')): ?>
                                <div class="alert alert-danger alert-dismissable">
                                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                    <h4><i class="icon fa fa-times"></i>Error!</h4>
                                    <?= Yii::$app->session->getFlash('cart_error') ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="product-slider">
                                <img src="<?php echo str_replace('150',500,$Product['image']);?>">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="product-detail">
                                <div class="prodct-tilte">
                                    <small><?= !empty($Product['brand'])?$Product['brand']:"";?></small>
                                    <h2><?= !empty($Product['name'])?$Product['name']:"";?></h2>
                                </div>
                                <div class="product-price">
                                    <span class="price-product">Rs <?= !empty($Product['price'])?$Product['price']:"";?>
                                        <span>price</span>
                                    </span>
                                    <span class=" text-mute">Retail Price <span class="line-through">
                                        Rs <?= !empty($Product['retail_price'])?$Product['retail_price']:"";?></span>
                                        </span>
                                    
                                </div>
                                <div class="use-code">
                                    <span>use code saveoptia and pay only ₹49.99</span>
                                </div>
                                <div class="product-select">
                                <div class="row">
                                    <?php 
                                     $currentSlug =   Url::toRoute(['product/view','slug'=>$Product['slug']]);
                                    if(!empty($Product['size'])){
                                         
                                          $SizeOfComb= array();
                                          $combinationSize = Product::find()->where(
                                              ['AND',
                                                ['=','combination_id',$Product['combination_id']],
                                                ['=','flavour',$Product['flavour']],
                                             ])->asArray()->all();
                                             if(!empty($combinationSize)){
                                                    foreach($combinationSize as $ele){
                                                            $slug   = Url::toRoute(['product/view','slug'=>$ele['slug']]);
                                                            $SizeOfComb[$slug] = $ele['size'];
                                                    } 
                                             }

                                        ?>
                                        <div class="col-md-6">
                                            <label>Size</label>
                                            <?= Html::dropDownList('list',$currentSlug,$SizeOfComb,
                                            ['class'=>'form-control','id'=>'sel1']); ?>          
                                        </div>
                                    <?php } ?>
                                    <?php if(!empty($Product['flavour'])){ 
                                           $FlavourOfComb= array();
                                           $combinationFlavour = Product::find()->where(
                                            ['AND',
                                              ['=','combination_id',$Product['combination_id']],
                                              ['!=','flavour',''],
                                              ['=','size', $Product['size']],
                                           ])->asArray()->all();
                                            if(!empty($combinationFlavour)){
                                                foreach($combinationFlavour as $ele){
                                                        $slug   = Url::toRoute(['product/view','slug'=>$ele['slug']]);
                                                        $FlavourOfComb[$slug] = $ele['flavour'];
                                                } 
                                            }
                                        ?>
                                        <div class="col-md-6">
                                                <label>Flavor</label>
                                            <?= Html::dropDownList('list',$currentSlug,$FlavourOfComb,
                                            ['class'=>'form-control','id'=>'sel1']) ?>          
                                        </div> 
                                    <?php } ?>                         
                                  </div>    
                                   
                                </div>
                                <div class="prodct-cart-btn" id="<?=$Product['sku'];?>">
                                  <?= Html::beginForm(['/cart/add-to-cart'], 'get',['class'=>'add-to-cart-form','data-sku'=>$Product['sku']]) ?>
                                    <div class="product-cart-incres">
                                        <div class="input-group">
                                            <?= Html::input('text',   'qty','1', ['class' => "form-control input-number","min"=>"1","max"=>"100"]);?>
                                            <?= Html::input('hidden', 'sku', $Product['sku']);?>
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-success btn-number" data-type="plus" data-field="qty">
                                                    <span class="glyphicon glyphicon-plus"></span>
                                                </button>
                                            </span>
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-danger btn-number" data-type="minus" data-field="qty">
                                                    <span class="glyphicon glyphicon-minus"></span>
                                                </button>
                                            </span>

                                        </div>
                                    </div>
                                    <div class="prodcut-btnCart">
                                          <?= Html::submitButton('ADD TO CART', ['class' => 'atc-btn-center']) ?>
                                    </div>
                                    <?= Html::endForm() ?>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>



        </section>
        <?php if(!empty($ProductRelated)){?>
        <section class="categoryMainContent">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="vieweditems">
                            <h2>Customers who viewed this product also viewed</h2>
                        </div>
                    </div>
                    <div class="col-lg-12 similaritemsList">
                        <ul>
                            <?php foreach($ProductRelated as $ele){?>
                                <li>
                                    <div class="cat-product-con">
                                        <div class="catImg">
                                              <?= Html::a(Html::img(Yii::$app->request->baseUrl.'/img/'.$ele['image']), array('/product/view','slug'=>$ele['slug'])); ?> 
                                        </div>
                                        <h1>
                                        <?= Html::a($ele['name'], array('#')); ?>                                             
                                        </h1>
                                        <h5>$ <?php echo $ele['price'];?></h5>
                                        <a href="#" class="addtocart">Add to Cart</a>

                                    </div>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <?php } ?>
        <section class="productDetailsCon">
            <div class="container">
                <div class="row">
                <div class="pro_dec_title"><h3>Product
                                <span>Info</span>
                                <small>(<b>SKU</b>- <?= !empty($Product['sku'])?$Product['sku']:"";?>)</small>
                            </h3></div>
                    <?= !empty($Product['description'])?$Product['description']:"";?>
                </div>
            </div>
        </section>
    <?php
       $this->registerJs(
        "$(document).on('change','#sel1',function() { 
                var v = $(this).val();
                window.location.href = v;
        });"
    );
    ?>
    <?php Pjax::end() ?>