common/models/Cart.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "cart".
 *
 * @property string $cart_unique_no
 * @property int $id
 * @property int $created_at
 * @property int $customer_id
 * @property int $payment_card_id
 * @property int $shipping_id
 *
 * @property CartContent[] $cartContents
 */
class Cart extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cart';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'customer_id', 'payment_card_id', 'shipping_id'], 'integer'],
            [['cart_unique_no'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'cart_unique_no' => 'Cart Unique No',
            'id' => 'ID',
            'created_at' => 'Created At',
            'customer_id' => 'Customer ID',
            'payment_card_id' => 'Payment Card ID',
            'shipping_id' => 'Shipping ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCartContents()
    {
        return $this->hasMany(CartContent::className(), ['cart_id' => 'id']);
    }
}

frontend/controllers/CartController.php
<?php
namespace frontend\controllers;
use \common\models\Product;
use \common\models\Cart;
use \common\models\Customer;
use \common\models\MapCardCustomerCart;
use \common\models\PaymentCard;
use \common\models\Order;
use \common\models\OrderDetaills;
use \yii\helpers\Html;
use yii\widgets\ActiveForm;

use Yii;

class CartController extends \yii\web\Controller

{
     public $enableCsrfValidation = false;
	 private function prepare(){
		$action   =  Yii::$app->controller->action->id;
        if(Yii::$app->cart->cartId() == 0){			
            Yii::$app->session->setFlash('info','Please add item in cart.');
            return $this->redirect(['/site/index']);
        }else{
			switch($action){
				case 'shipping':
					$Customer = Yii::$app->cart->CustomerInCart();
					if($Customer['status'] == false || $Customer['customer_id'] == 0){
						 return $this->redirect(['/customer/create']);
					}
					break;
				case 'payment':
					$Customer = Yii::$app->cart->CustomerInCart();					
					if($Customer['status'] == false || $Customer['shipping_id'] == 0){
						 return $this->redirect(['/cart/shipping']);
					}					
					break;
			}
		}
        return ;
    }

    public function actionAddToCart($sku,$qty=1,$total_qty=0){  
       //
        $CartData = array('sku'=>$sku,'qty'=>$qty,'total_qty'=>$total_qty);
        $res =  Yii::$app->cart->AddToCart($CartData);
        
        $res['view_cart_holder_html']     = "";
        if($res['status']== true){
            $Product 		             =   Product::find()->where(['sku'=>$sku])->one();            
            $res['html']                 =   $this->renderAjax('_ajax_cart',[
							 	        	    'Product'   =>  $Product,
                                            ]);
            if($total_qty > 0){
                $res['view_cart_holder_html']     =    $this->renderAjax('//cart/_cart-items');
            }
            $res['header_cart_html']     =   $this->renderAjax('//cart/_header_cart');
        }else{

              Yii::$app->session->setFlash('cart_failed', $res['message']);

        }
		echo json_encode($res);die;
    }

    public function actionRemoveCart($sku){
        $CartData = array('sku'=>$sku);
        $res =  Yii::$app->cart->RemoveItemFromCart($CartData);  
        if($res['status']== true){
            $res['view_cart_holder_html']     =    $this->renderAjax('//cart/_cart-items');
            $res['header_cart_html']          =    $this->renderAjax('//cart/_header_cart');
        }else{
            Yii::$app->session->setFlash('view_cart_failed', $res['message']);
        }
        echo json_encode($res);die;
    }
    public function actionViewCart()

    {

        $this->prepare();

        return $this->render('cart');

    }

	 public function actionPayment(){
		$this->prepare();
        $model = new PaymentCard();         
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format =  \yii\web\Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $res = Yii::$app->cart->placeOrder($model->id);    

            return $this->redirect(['confirmation','order_id'=>$res['order_id']]);  

        }

        return $this->render('payment', [

            'model' => $model,

        ]);



        return $this->render('payment');

    }

	 public function actionConfirmation($order_id)

    {
		
        $model = Order::find()->select(['order.*','payment_card.type as type'])
                ->leftJoin('payment_card','order.paymen_card_id = payment_card.id')
                ->where(['order.order_no'=>$order_id])->asArray()
                ->one();
        $OrderDetaills  =   OrderDetaills::find()->select(['product.*','order_detaills.*'])->where(['order_id'=>$model['id']])
                             ->leftJoin('product', 'order_detaills.product_id=product.id')->asArray()
                             ->all();


        return $this->render('confirmation',['model'=> $model,'OrderDetaills'=>$OrderDetaills]);

    }

	public function actionShipping(){		
         $this->prepare();
         return $this->render('shipping');

    }
    public function actionAddShipping(){	
        $res = array('status'=>false,'message'=>'Please select shipping method.','next_button'=>"");
        if (!empty($_POST['shipping_method'])) {
            $res = Yii::$app->cart->AddShippingToCart(array('shipping_id'=>$_POST['shipping_method']));    	
            $res['status']                 =    true;
            $res['_cart_sidebar_html']     =    $this->renderAjax('//cart/_cart_sidebar');
            $res['next_button']            =    Html::a('NEXT',['/cart/payment'],['class' => 'checkout-btn btn-continue']);                      
        }		
        echo json_encode($res);die;

    }
    public function actionExistCustomer(){
        $res['status']            = false;
        $res = Yii::$app->cart->CustomerInCart(); 
        if($res['customer_id'] == 0){
            $model  = Customer::find()->where(['email'=>$_POST['email']])->one();
            if(!empty($model)){
                $res['customer_form']     =    $this->renderAjax('//cart/_customer_form',['model'=>$model]);
                $res['status']            = true;
            }
        }
        echo json_encode($res);
    }
    public function actionCustomer()
    {
        $res = Yii::$app->cart->CustomerInCart(); 
        if($res['status']==true && !empty($res['customer_id']) && $res['customer_id'] > 0){
            $model  = Customer::find()->where(['id'=>$res['customer_id']])->one();
        }else{
            $model = new Customer();   
        } 
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $CustomerData   = array('customer_id'=>$model->id);
            $res = Yii::$app->cart->AddCustomerToCart($CustomerData);
            if($res['status']== true){
                return $this->redirect(['cart/shipping']);
            }else{
                Yii::$app->session->setFlash('customer_failed', $res['message']);
            }           
        }

         
        return $this->render('customer', [
            'model' => $model,
        ]);
    }

}

?>

frontend/views/cart/_ajax_cart.php
<?php

use yii\helpers\Html;
?>
<div class="click-productVBox">
  <div class="close-cart"></div>
  <div class="productVBox-BG">
    <div class="VBox-BG-title">
      <h3>Added to cart</h3>
    </div>
    <div class="VBox-BG-prodct">
      <div class="row">
        <div class="col-md-8">
          <div class="VBox-BG-product">
            <?= Html::a(Html::img($Product->image), array('/product/view','slug'=>$Product->slug)); ?>
           </div>
          <div class="BG-product-text"> <span class="name-product-text"><?=$Product->name;?></span> <span class="name-product-qty">Quantity:<?= Yii::$app->cart->productQty($Product->sku);?></span> </div>
        </div>
        <div class="col-md-4">
          <div class="BG-product-price"><span class="product-price">Rs <?=$Product->price;?></span></div>
        </div>
        <div class="total-BG-product clearfix"> <span class="pull-left"><?= Yii::$app->cart->itemCount();?> item in cart</span> 
            <span class="pull-right">Subtotal Rs <?= Yii::$app->cart->CartTotal();?></span> 
        </div>
        <div class="btn-BG-product clearfix"> 
          <?= Html::a('View cart',['/cart/view-cart'],['class'=>'product-view-btn']);?>
          <?= Html::a('Check out',['/customer/create'],['class'=>'product-checkout-btn']);?>
         </div>
      </div>
    </div>
  </div>
</div>

frontend/views/cart/_cart-items.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
$CartTotal = Yii::$app->cart->CartTotal();
?>
<div class="shoping-cart-main">
    <?php
        $CartList = Yii::$app->cart->CartList();      
        if(!empty($CartList)){

    ?>
        <div class="tital-btn clearfix">
            <div class="title-cart">
                <h1>Shopping cart</h1>
            </div>
            <div class="cart-check-btn">
            <?= Html::a('Check out now', ['/cart/customer'],['class' => 'checkout-btn']) ?>
            </div>
        </div>
        <div class="cart-product-div clearifx">
          <div class="col-md-12">      
            <div class="row">
              <div id="view_cart_holder_html" class="row">
                    <div class="bg-product-wht">
                    <?php
                        $retail=0;
                        foreach($CartList as $ele){
                          $retail = $retail+($ele['retail_price'] * $ele['qty']);
                    ?>
                    <div class="product-box-cart">
                    <div class="row">
                        <div class="col-md-9">
                          <div class="product-cart-img clearfix">
                            <div class="img-cart">
                              <?= Html::a(Html::img($ele['image']),array('product/view','slug'=>$ele['slug']),['target'=>'_blank','class'=>'text-decoration-none']); ?>
                              <div class="remove-product">
                                  <?= Html::a('<span><i class="glyphicon glyphicon-remove"></i></span> Remove','javascript:void(0);',['class'=>'remove-from-cart','sku'=>$ele['sku']]); ?>    
                              </div>
                            </div>
                            <div class="cart-img-data">
                                <?= Html::a('<span class="vitmsapn">'.$ele['brand'].'</span>
                              <h4 class="cart-title-img">'.$ele['name'].'</h4>
                              <span class="vitmsapn-item"> Item #: '.$ele['sku'].'</span>',array('product/view','slug'=>$ele['slug']),['target'=>'_blank','class'=>'text-decoration-none']); ?>
                              
                            </div>
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="gray-bg-incras">
                            <div class="incres-price-light">
                              <span>Rs <?= $ele['price'];?></span>
                            </div>
                            <div class="incres-div">
                              <div class="input-group">
                                <div class="inputdiv">
                                    <?= Html::input('text',   'qty['.$ele['sku'].']',$ele['qty'], ['class' => "form-control cart-qty","min"=>"1","max"=>"100",'data-sku' =>$ele['sku']]);?>
                                </div>
                                <div class="inputdiv-btn">
                                  <span class="input-group-btn">
                                  <button type="button" class="btn btn-number" data-type="plus" data-field='qty[<?=$ele['sku'];?>]' > <span class="glyphicon glyphicon-plus"></span> </button>
                                  </span> <span class="input-group-btn">
                                  <button type="button" class="btn btn-number"  data-type="minus"  data-field='qty[<?=$ele['sku'];?>]' > <span class="glyphicon glyphicon-minus"></span> </button>
                                  </span>
                                </div>
                              </div>
                            </div>
                            <div class="incres-price-dark">
                            <span>Rs <?= $ele['price'] * $ele['qty'];?></span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                      <?php }  ?> 
                  </div>
                  <div class="bg-product-wht-total">
                    <div class="price-box-podcut clearifx">
                      <div class="onewht-total clearifx">
                        <span class="left-sec-product"> subtotal </span> <span class="right-sec-product"> Rs <?=  $CartTotal;?> </span>
                      </div>
                      <div class="onewht-total clearifx">
                        <span class="left-sec-product"> Estimated shipping </span> <span class="right-sec-product">Free</span>
                      </div>
                      <div class="onewht-total clearifx">
                        <span class="left-sec-product"> tax varies by address </span> <span class="right-sec-product">Included IGST</span>
                      </div>
                      <?php
                          $saved = $retail-$CartTotal;
                          if($saved>0){
                      ?>
                      <div class="onewht-total clearifx">
                        <span class="left-sec-product color-red"> You saved </span> <span class="right-sec-product color-red">Rs <?= Html::encode(number_format($saved));?></span>
                      </div>
                      <?php  } ?>
                      <div class="onewht-total sub-blue clearifx">
                        <span class="left-sec-product"> <span class="icon-abou"><i class="glyphicon glyphicon-question-sign"></i></span> Estimated order total </span> <span class="right-sec-product"> $ <?=  Yii::$app->cart->CartTotal();?></span>
                      </div>
                    </div>
                  </div>
                  </div>
                <div class="cart-check-btn sec-check-btn">
                        <?= Html::a('Check out now', ['/cart/customer'],['class' => 'checkout-btn']) ?>
                </div>            
            </div>
          </div>
        </div>
   <?php  } else{?>
        <div class="row">
                <div class="col-md-12 cart-is-empty">
                      <i class="fa fa-shopping-cart"></i>
                      <h2 class="text-center text-mute"> Your Cart Is Empty</h2> 
                                      
                      <?= Html::a('Continue Shopping', ['/site/index'],['class' => 'checkout-btn m-t-20']) ?> 
                 </div>
         </div>
   <?php } ?>
</div>

frontend/views/cart/_cart_sidebar.php
<?php
$CustomerInCart = Yii::$app->cart->CustomerInCart();
?>
<div class="gray-bg-incras">
                      <div class="ul-div">
                        <ul class="order-ul clearfix">
                          <li>
                            <span class="pull-left">Subtotal</span> <span class="pull-right">Rs <?= Yii::$app->cart->CartTotal();?></span>
                          </li>
                          <li>
                            <span class="pull-left">Shipping</span> <span class="pull-right">Rs <?= number_format(Yii::$app->cart->shippingCal($CustomerInCart['shipping_id'],$WantTotatal=1));?></span>
                          </li>
                          <li>
                            <span class="pull-left">Tax</span> <span class="pull-right">$ 0.00</span>
                          </li>
                          <li class="reward-li">
                            <span class="pull-left">Reward</span> <span class="pull-right">($ 0.00)</span>
                          </li>
                        </ul>
                        <ul class="order-ul br-none clearfix">
                          <li>
                            <span class="pull-left">Order Total</span> <span class="pull-right">Rs <?= number_format(Yii::$app->cart->CartTotal() + Yii::$app->cart->shippingCal($CustomerInCart['shipping_id'],$WantTotatal=1));?></span>
                          </li>
                        </ul>
                        <p class="will-order-text">You Will be able to review and modify your order on the review page</p>
        </div>
</div>

frontend/views/cart/_customer_form.php

<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h2>add new shipping Address</h2>   
<?php
$form = ActiveForm::begin(['class'=>'form-shiping','action'=>['/cart/customer']]); ?>
    <div class="row">
                         <div class="col-md-12">                            
                            <?php if (Yii::$app->session->hasFlash('customer_failed')): ?>
                                <div class="alert alert-danger alert-dismissable">
                                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                    <h4><i class="icon fa fa-times"></i>Error!</h4>
                                    <?= Yii::$app->session->getFlash('customer_failed') ?>
                                </div>
                            <?php endif; ?>
                        </div>
     </div>
    <div class="group-div">
        <?= $form->field($model, 'email')->textInput(['class' => 'input-form-shipping','placeholder'=>'Email'])->label(false); ?>
    </div>
    <div class="group-div">
            <?= $form->field($model, 'fullname')->textInput(['class' => 'input-form-shipping','placeholder'=>'Full Name'])->label(false); ?>
    </div>
    <div class="group-div">
         <?= $form->field($model, 'adress')->textArea(['class' => 'input-form-shipping add-text-area','placeholder'=>'Address'])->label(false); ?>
    </div>
    <div class="group-div">
         <?= $form->field($model, 'city')->textInput(['class' => 'input-form-shipping','placeholder'=>'City'])->label(false); ?>
    </div>
    <div class="group-div clearfix selecrtR">
         <?= $form->field($model, 'state')->dropDownList($model->state_list,['class' => 'input-form-shipping','placeholder'=>'State','prompt'=>'Select your state'])->label(false); ?>
    </div>
    <div class="group-div zip-code clearfix">
         <?= $form->field($model, 'zipcode')->textInput(['class' => 'input-form-shipping','placeholder'=>'Zipcode'])->label(false); ?>
    </div>
    <div class="group-div">
           <?= $form->field($model, 'phone')->textInput(['class' => 'input-form-shipping','placeholder'=>'Phone'])->label(false); ?>
    </div>
    <div class="btn-form">
        <div class="btn-confurm">
                <?= Html::submitButton('Continue', ['class' => 'checkout-btn btn-continue']) ?>
        </div>
        <div class="btn-cancel">
                 <button type="reset" class="checkout-btn btn-cancel" >Cancel</button>
        </div>
   </div>

    <?php ActiveForm::end(); ?>

frontend/views/cart/_header_cart.php
<?php  
use yii\helpers\Html;                                 
$CartList = Yii::$app->cart->CartList();
$CartCount  =   Yii::$app->cart->itemCount();
?>
<a href="javascript:toggleDiv('myContent1');">
    <span class="count"><?=  Yii::$app->cart->itemCount();?></span>
    <i></i>
</a>
<section class="dropCart" id="myContent1" style=" display:none">    
    <p><?= $CartCount>0 ? $CartCount." items in your cart":"There are no item in cart.";?> </p>
    <hr>
    <?php if(!empty($CartList)){?>		
        <div class="clearfix"></div> 
        <div class="cart-maindiv">
                <ul class="cart-ul">  
                    <?php foreach($CartList as $ele){?>    
                        <li>
                            <div class="li-product clearfix">
                                <div class="img-cart-div">
                                        <?=Html::img($ele['image']);?>
                                </div>
                                <div class="data-cart-div">
                                        <span class="product-title"><?= $ele['brand'];?></span>
                                        <span class="product-name"><?= $ele['name'];?></span>
                                    <span class="product-qty">Qty : <?= $ele['qty'];?>  | Price : Rs <?= $ele['price'];?></span>
                                </div>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
        </div> 
        <div class="clearfix"></div>  
        <div class="subtotal">
                <h3>Subtotal Rs <?=  Yii::$app->cart->CartTotal();?></h3>
        </div>
        <div class="btn-checkout">
                <?= Html::a('view cart & check out', array('cart/view-cart'),['class'=>'btn-site check-out']); ?>  
        </div>
    <?php } ?>
</section>								

frontend/views/cart/cart.php
  <?php
  /* @var $this yii\web\View */
  use yii\helpers\Html;
  ?>
 <section>
    <div class="container" id="view-cart-section">
          <?= $this->render('_cart-items');?>
    </div>
  </section>
  <?php
  $this->registerJs(
    "
     $(document).on('change','.cart-qty',function () {      
          var minValue = parseInt($(this).attr('min'));
          var maxValue = parseInt($(this).attr('max'));
          var sku      = $(this).attr('data-sku')
          if (!minValue) minValue = 1;
          if (!maxValue) maxValue = 50;
          var valueCurrent = parseInt($(this).val());
          
          var name = $(this).attr('name');
          if (valueCurrent >= minValue) {
              $('.btn-number[data-type=\'minus\'][data-field=\'name\']').removeAttr('disabled')
          } else {
              $(this).val($(this).data('oldValue'));
          }
          if (valueCurrent <= maxValue) {
              $('.btn-number[data-type=\'plus\'][data-field=\'name\']').removeAttr('disabled')
          } else {
              $(this).val($(this).data('oldValue'));
          } 
          if($(this).val()>0){
              call({ url: '/cart/add-to-cart', params: { 'sku': sku,'qty':0,'total_qty':$(this).val()}, type: 'GET' }, function(resp) {      

                  if (resp.status == true) {
                     $('#header-cart').html(resp.header_cart_html);
                     $('#view-cart-section').html(resp.view_cart_holder_html);
                     
                  }

              });
          }else{
            $(this).val(1); 
          }

      });
      $(document).on('keydown','.cart-qty',function (e) {
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||       
            (e.keyCode == 65 && e.ctrlKey === true) ||
            (e.keyCode >= 35 && e.keyCode <= 39)) {
            return;
        }
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode >105)) {
            e.preventDefault();
        }
      });"
  );
  ?>
  

frontend/views/cart/customer.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Customer */
/* @var $form yii\widgets\ActiveForm */
?>

<section>
    <div class="container">
      <div class="shoping-cart-main">
        <div class="tital-btn clearfix">
          <div class="title-cart">
            <h1>Shipping Address</h1>
          </div>
          <div class="cart-check-btn add-summary">
            <h3>Order Summary</h3>
          </div>
        </div>
        <div class="cart-product-div clearfix">
          <div class="col-md-12">
            <div class="row">
              <div class="bg-product-wht form-BG">
                <div class="row">
                  <div class="col-md-6">
                    <div class="Shiping-form" id="customer-form">                          
                          <?= $this->render( '_customer_form',['model'=>$model]); ?>
                    </div>
                  </div>
                  <div class="col-md-offset-3 col-md-3 col-sm-offset-3">
                       <?= $this->render( '_cart_sidebar'); ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <?php
  $this->registerJs("
     $(document).on('blur','#customer-email',function () {      
      call({ url: '/cart/exist-customer', params: { 'email':$(this).val()}, type: 'POST' }, function(resp) { 
        if (resp.status == true) {
           $('#customer-form').html(resp.customer_form);           
        }

    });

     });
    " );?>

frontend/views/cart/shipping.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use \common\models\Customer;
use \common\models\ShippingService;
$Customer = Yii::$app->cart->CustomerInCart();
?>

  <section>
    <div class="container">
      <div class="shoping-cart-main">
        <div class="tital-btn clearfix">
          <div class="title-cart">
            <h1>Shipping Details</h1>
          </div>
          <div class="cart-check-btn add-summary">
            <h3>Order Summary</h3>
          </div>
        </div>
        <div class="cart-product-div clearfix">
          <div class="col-md-12">
            <div class="row">
              <div class="bg-product-wht form-BG">
                <div class="row">
                  <div class="col-md-9">
                    <div class="Shiping-form">
                      <div class="row">
                        <div class="col-md-8">
                          <?php
                            $ShippingService = ShippingService :: find()->where(['status'=>1])->all();
                             if(!empty($ShippingService)){
                               
                          ?>
                          
                           <h2>Available shipping methods</h2>

                            <?php foreach($ShippingService as $ele){ 
                                  $res      = Yii::$app->cart->shippingCal($ele['id']); 
                                  $checked  = $Customer['shipping_id']==$ele['id']?'checked':"";                            
                              ?>
                                <label class="check-cate-box clearfix" for="<?php echo $ele['id'];?>">
                                  <div class="prof-checker radioDiv">
                                    <input class="radio-input" <?php echo $checked;?>  type="radio" name="shipping_method" value="<?php echo $ele['id'];?>"  id="<?php echo $ele['id'];?>" >
                                  </div>
                                  <div class="data-radiosec clearfix">
                                    <div class="img-radio">
                                        <?=Html::img(Yii::$app->request->baseUrl.'/'.$ele['image']);?>
                                    </div>
                                    <div class="data-text">
                                          <span class="radio-Title"><?php echo $ele['name'];?> - <small><?php echo $ele['price_text'];?></small></span>
                                          <span class="radio-subtitle">expirated delivery : <?php echo $res['day'];?></span>                                           
                                    </div>
                                  </div>
                                </label>
                            <?php } ?>    

                            <div class="btn-confurm m-t-20" id="next-btn">                                
                                            <?php echo $checked=="checked"?  Html::a('NEXT',['/cart/payment'],['class' => 'checkout-btn btn-continue']):"";   ?>
                            </div>


                          <?php } ?>
                        </div>
                        <div class="col-md-4">
                          <h2>Select Shipping Address</h2>
                          <div class="add-box-shiping">
                          	<?php 
								if(!empty($Customer['status'])){
									$Customer = Customer::find()->where(['id'=>$Customer['customer_id']])->asArray()->one();
									echo '<p class="name-add"><span>'.Html::encode($Customer['fullname']).'</span> '.Html::encode($Customer['adress']).','.Html::encode($Customer['city']).','.Html::encode($Customer['state']).','.Html::encode($Customer['zipcode']).'</p>';
								}else{
									echo '<p class="name-add">'.$Customer['message'].'</p>';
								}
							?>
                             <div class="btn-confurm btn-delt">         
                               <?= Html::a('change Address',['/cart/customer'],['class' => 'checkout-btn btn-continue']) ?>                                                                                     
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-3" id="_cart_sidebar_html">
                       <?= $this->render( '_cart_sidebar'); ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <?php
$this->registerJs(
"
  $(document).on('change','input[type=radio][name=shipping_method]',function() {
   
     call({ url: '/cart/add-shipping', params: { 'shipping_method':$(this).val()}, type: 'POST' }, function(resp) {    
        if(resp.status == true){
          $('#_cart_sidebar_html').html(resp._cart_sidebar_html);
          $('#next-btn').html(resp.next_button);
        }else{        
        }
     });
  });
"


)
  ?>